name: Release Obsidian Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get version from tag  
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Verify plugin files exist
        run: |
          if [[ ! -f "main.js" ]]; then echo "main.js not found"; exit 1; fi
          if [[ ! -f "manifest.json" ]]; then echo "manifest.json not found"; exit 1; fi
          if [[ ! -f "styles.css" ]]; then echo "styles.css not found"; exit 1; fi
          if [[ ! -f "versions.json" ]]; then echo "versions.json not found"; exit 1; fi
          echo "All plugin files verified ✅"
      
      - name: Create plugin zip
        run: |
          # Create folder with plugin name
          mkdir granola-sync
          
          # Copy plugin files to folder
          cp main.js granola-sync/
          cp manifest.json granola-sync/
          cp styles.css granola-sync/
          cp versions.json granola-sync/
          
          # Create zip file with just version number
          zip -r ${{ steps.version.outputs.VERSION }}.zip granola-sync/
          
          # Verify zip was created
          ls -la *.zip
          echo "Plugin zip created: ${{ steps.version.outputs.VERSION }}.zip ✅"
          
      - name: Create GitHub Release
        run: |
          gh release create v${{ steps.version.outputs.VERSION }} \
            --title "Granola Sync v${{ steps.version.outputs.VERSION }}" \
            --notes "## 🚀 Granola Sync v${{ steps.version.outputs.VERSION }}
            
            ### 📦 Installation Options
            
            **Option 1: Download ZIP (Recommended)**
            1. Download \`${{ steps.version.outputs.VERSION }}.zip\`
            2. Extract the \`granola-sync\` folder to \`.obsidian/plugins/\` in your vault
            3. Enable the plugin in Obsidian Settings → Community Plugins
            
            **Option 2: Manual Installation**  
            1. Download individual files: \`main.js\`, \`manifest.json\`, \`styles.css\`, \`versions.json\`
            2. Create folder \`.obsidian/plugins/granola-sync/\` in your vault
            3. Place all files in the folder
            4. Enable the plugin in Obsidian Settings → Community Plugins
            
            ---
            
            For detailed changelog and features, see the [README](https://github.com/dannymcc/Granola-to-Obsidian/blob/main/README.md)." \
            main.js manifest.json styles.css versions.json ${{ steps.version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
